#!/usr/bin/env python3
"""Download training datasets.

Datasets by training stage:
  Stage 1 (Adapter):  LibriSpeech clean-100  (100h speech + transcripts)
  Stage 2 (LoRA):     VoiceAssistant-400K    (400K instruction pairs)
  Stage 3 (Probe):    GoEmotions             (58K texts, 28 emotion labels)
  Stage 4 (Connect):  Synthetic (self-generated) — no download needed

Usage:
  python scripts/download_data.py           # download all
  python scripts/download_data.py --stage 1 # download Stage 1 only
  python scripts/download_data.py --stage 3 # download Stage 3 only
"""

import os
import argparse


def download_stage1():
    """LibriSpeech clean-100 for adapter pretraining."""
    from datasets import load_dataset
    print("[Stage 1] Downloading LibriSpeech clean-100...")
    ds = load_dataset("librispeech_asr", "clean", split="train.100")
    ds.save_to_disk("data/librispeech_clean100")
    print(f"  Saved {len(ds)} samples to data/librispeech_clean100")


def download_stage2():
    """VoiceAssistant-400K for Thinker LoRA tuning."""
    from datasets import load_dataset
    print("[Stage 2] Downloading VoiceAssistant-400K...")
    ds = load_dataset("gpt-omni/VoiceAssistant-400K")
    ds.save_to_disk("data/voiceassistant_400k")
    print(f"  Saved to data/voiceassistant_400k")


def download_stage3():
    """GoEmotions for emotion probe training."""
    from datasets import load_dataset
    print("[Stage 3] Downloading GoEmotions (58K texts, 28 emotions)...")
    ds = load_dataset("google-research-datasets/go_emotions")
    ds.save_to_disk("data/goemotions")
    print(f"  Saved to data/goemotions")


def main():
    parser = argparse.ArgumentParser(description="Download training datasets")
    parser.add_argument("--stage", type=int, choices=[1, 2, 3],
                        help="Download data for specific stage only (Stage 4 uses synthetic data)")
    args = parser.parse_args()

    os.makedirs("data", exist_ok=True)

    if args.stage is None or args.stage == 1:
        download_stage1()
    if args.stage is None or args.stage == 2:
        download_stage2()
    if args.stage is None or args.stage == 3:
        download_stage3()

    print("\nDone!")
    if args.stage is None:
        print("\nNote: Stage 4 uses synthetic data generated by the training pipeline.")
        print("Run: python -m src.training.generate_connector_data --help")


if __name__ == "__main__":
    main()
